on:
  push:
    branches: ["main"]

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    name: Sync Repository from GitHub to GitLab
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/sync-github-to-gitlab-action@main
        with:
         destination_repository: git@gitlab.com:batyrhoja/dc3.git
         destination_branch_name: main
         destination_ssh_key: ${{ secrets.SHA256:ROQFvPThGrW4RuWLoL9tq9I9zJ42fK4XywyRtbOz/EQ }}
